// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMUdqfu_-L1lUop9OXOF0a4YJPmdtYlTw',
    appId: '1:1000471887763:web:0f12b6cd4ae26d5e04b266',
    messagingSenderId: '1000471887763',
    projectId: 'pesquisa2024-44459',
    authDomain: 'pesquisa2024-44459.firebaseapp.com',
    storageBucket: 'pesquisa2024-44459.appspot.com',
    measurementId: 'G-VVXFF9VHEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxjGg9AsHcjPXYr56WU1wrtrqdC7g8Rlo',
    appId: '1:1000471887763:android:4f5a94ccfda4866c04b266',
    messagingSenderId: '1000471887763',
    projectId: 'pesquisa2024-44459',
    storageBucket: 'pesquisa2024-44459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuEFIhzxqOuGA3_Y0OdUGcegHWGWVT9bI',
    appId: '1:1000471887763:ios:1281122f0b253ff004b266',
    messagingSenderId: '1000471887763',
    projectId: 'pesquisa2024-44459',
    storageBucket: 'pesquisa2024-44459.appspot.com',
    iosClientId: '1000471887763-m3n8uiou5hgoavlc15bd78pd38igpr9j.apps.googleusercontent.com',
    iosBundleId: 'br.com.devteamweb.opsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuEFIhzxqOuGA3_Y0OdUGcegHWGWVT9bI',
    appId: '1:1000471887763:ios:d4d965ed0d01f0c604b266',
    messagingSenderId: '1000471887763',
    projectId: 'pesquisa2024-44459',
    storageBucket: 'pesquisa2024-44459.appspot.com',
    iosClientId: '1000471887763-l1iuvhl2k76lbetcqt1dv3vqmhs1nq2n.apps.googleusercontent.com',
    iosBundleId: 'br.com.devteamweb.opsystem.RunnerTests',
  );
}
